AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a web server with cfn-init and cfn-hup, serving a custom HTML page

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default: ["install", "configure"]
        install:
          packages:
            yum:
              httpd: []
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |